In [1]:
# Consider the below code to answer further questions:
import numpy as np
list_ = ['1', '2' , '3' , '4' , '5']
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [2]:
# Question : 01 Is there any difference in the data type of variables list_ and array_list? If there is then write a code  to print the data types of both the variables.

# Answer : 
# List : a list is a built-in data type that can hold an ordered collection of items of any type. Lists are created using square brackets ([]). size of list is not fixed and we can changes on this.

# ArrayList : on the other hand  arrays are fixed-size arrays and can contain elements of the same data type. 

l = [1, 2, 3, 4, ]
arr = np.array(l)
arr

array([1, 2, 3, 4])

In [3]:
# changing element :
l[0] = 4234
arr[0] = 4234
l
arr

array([4234,    2,    3,    4])

In [4]:
l.append(43243)
l

[4234, 2, 3, 4, 43243]

In [5]:
# size is fixed in case of array ,  so can't add new element only , we can update
arr.append(324234)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [6]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.
print("Data type of each and every element in the list:")
for data in list_:
    print(type(data))

Data type of each and every element in the list:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
print("Data type of each and every element in the array:")
for element in array_list:
    print(type(element))

Data type of each and every element in the array:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list?
# If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [9]:
list_

['1', '2', '3', '4', '5']

In [10]:
array_list

array([1, 2, 3, 4, 5])

In [11]:
type(list_)

list

In [12]:
type(array_list)

numpy.ndarray

In [15]:
print("Data type of each and every element of list:")
for data in list_:
    print(type(data))

Data type of each and every element of list:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [16]:
print("Data type of each and every element in array_list:")
for element in array_list:
    print(type(element))

Data type of each and every element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [17]:
# Nothing changes happen in the variable list_ , but in case of array_list  , we change the data type from string to int

In [18]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [20]:
type(num_list)

list

In [21]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
type(num_array)

numpy.ndarray

In [25]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
num_array.shape

(2, 3)

In [26]:
# (ii) size
num_array.size

6

In [29]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
arr_idt = np.eye(5)
arr_idt

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])