In [1]:
import numpy as np

In [2]:
# Sort , Search and Counting Functions.

In [3]:
arr = np.array([2,3,4,6,5,6,8,0,-7,9,5,-3])

In [4]:
arr

array([ 2,  3,  4,  6,  5,  6,  8,  0, -7,  9,  5, -3])

In [5]:
np.sort(arr)

array([-7, -3,  0,  2,  3,  4,  5,  5,  6,  6,  8,  9])

In [10]:
np.searchsorted(arr,25)
# konse index par data inser hoga

12

In [12]:
arr1 = np.array([0,23,54,23,7,0,5,0,7,0,0,4,2,4,6])

In [13]:
np.count_nonzero(arr1)

10

In [14]:
np.where(arr>6)
# gives index , where condition satisfy

(array([6, 9]),)

In [16]:
np.extract(arr>3,arr)

array([4, 6, 5, 6, 8, 9, 5])

In [17]:
# Numpy -  Byte Swapping

In [18]:
arr

array([ 2,  3,  4,  6,  5,  6,  8,  0, -7,  9,  5, -3])

In [19]:
arr.byteswap()

array([ 144115188075855872,  216172782113783808,  288230376151711744,
        432345564227567616,  360287970189639680,  432345564227567616,
        576460752303423488,                   0, -432345564227567617,
        648518346341351424,  360287970189639680, -144115188075855873])

In [20]:
# Numpy - Copies and Views

In [21]:
a = np.copy(arr)
# Deep copy

In [22]:
# Shallow copy can be acheive in another way
b = arr.view()

In [23]:
arr

array([ 2,  3,  4,  6,  5,  6,  8,  0, -7,  9,  5, -3])

In [24]:
b

array([ 2,  3,  4,  6,  5,  6,  8,  0, -7,  9,  5, -3])

In [25]:
b[0] =342

In [26]:
b

array([342,   3,   4,   6,   5,   6,   8,   0,  -7,   9,   5,  -3])

In [27]:
arr

array([342,   3,   4,   6,   5,   6,   8,   0,  -7,   9,   5,  -3])

In [29]:
# Numpy -  Metrix library

# all task which can be done using numpy can be acheive using metrix library

In [30]:
import numpy.matlib as nm

In [31]:
nm.zeros(5)
# Minimum 2-d

matrix([[0., 0., 0., 0., 0.]])

In [32]:
nm.ones((5,6))

matrix([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [33]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
# Numpy - Linear Algebra

In [35]:
arr1 = np.random.randint([[3,4],[6,4]])

In [36]:
arr2 = np.random.randint([[6,4],[1,3]])

In [37]:
np.dot(arr1,arr2)

array([[ 2,  6],
       [ 5, 15]])

In [38]:
arr1@arr2

array([[ 2,  6],
       [ 5, 15]])