In [1]:
import numpy as np

In [2]:
# Numpy - Array Manipulation.


In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[2, 9, 1, 3],
       [1, 3, 1, 1],
       [9, 3, 9, 7]])

In [5]:
arr.reshape(6,2)

array([[2, 9],
       [1, 3],
       [1, 3],
       [1, 1],
       [9, 3],
       [9, 7]])

In [7]:
arr.T

array([[2, 1, 9],
       [9, 3, 3],
       [1, 1, 9],
       [3, 1, 7]])

In [8]:
arr.flatten()
# convet data into 1-d

array([2, 9, 1, 3, 1, 3, 1, 1, 9, 3, 9, 7])

In [9]:
arr1 = np.array([1,2,3,4,5,6])

In [10]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1)
# axis =1 , expands accors to the column

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
arr

array([[2, 9, 1, 3],
       [1, 3, 1, 1],
       [9, 3, 9, 7]])

In [17]:
np.squeeze(arr)

array([[2, 9, 1, 3],
       [1, 3, 1, 1],
       [9, 3, 9, 7]])

In [18]:
data = np.array([[1],[2],[3]])

In [19]:
data

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 4, 5, 6])

In [22]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [25]:
np.roll(arr1 , 2)

array([5, 6, 1, 2, 3, 4])

In [27]:
np.diag(arr1)
# all data keep in the diogonal , and create a 2-d array

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [28]:
# Numpy - Binary Operations

In [29]:
arr1 = np.random.randint(1,10,(3,4))

In [30]:
arr2= np.random.randint(1,10,(3,4))

In [31]:
arr1

array([[6, 6, 6, 9],
       [8, 6, 7, 4],
       [2, 9, 1, 5]])

In [32]:
arr2

array([[2, 5, 8, 5],
       [9, 7, 8, 6],
       [8, 4, 4, 9]])

In [33]:
arr1+arr2

array([[ 8, 11, 14, 14],
       [17, 13, 15, 10],
       [10, 13,  5, 14]])

In [34]:
arr1*arr2

array([[12, 30, 48, 45],
       [72, 42, 56, 24],
       [16, 36,  4, 45]])

In [35]:
arr1/arr2

array([[3.        , 1.2       , 0.75      , 1.8       ],
       [0.88888889, 0.85714286, 0.875     , 0.66666667],
       [0.25      , 2.25      , 0.25      , 0.55555556]])

In [37]:
arr1-arr2

array([[ 4,  1, -2,  4],
       [-1, -1, -1, -2],
       [-6,  5, -3, -4]])

In [38]:
arr1%arr2
# give remender 

array([[0, 1, 6, 4],
       [8, 6, 7, 4],
       [2, 1, 1, 5]])

In [39]:
arr1**arr2

array([[       36,      7776,   1679616,     59049],
       [134217728,    279936,   5764801,      4096],
       [      256,      6561,         1,   1953125]])

In [40]:
arr1 & arr2
# AND operation

array([[2, 4, 0, 1],
       [8, 6, 0, 4],
       [0, 0, 0, 1]])

In [41]:
~arr1

array([[ -7,  -7,  -7, -10],
       [ -9,  -7,  -8,  -5],
       [ -3, -10,  -2,  -6]])

In [43]:
arr1 | arr2

array([[ 6,  7, 14, 13],
       [ 9,  7, 15,  6],
       [10, 13,  5, 13]])

In [44]:
arr1 > arr2

array([[ True,  True, False,  True],
       [False, False, False, False],
       [False,  True, False, False]])

In [45]:
# Numpy  -  String Functions.

In [46]:
arr = np.array(['sudh','kumar','pawan','krish'])

In [47]:
arr

array(['sudh', 'kumar', 'pawan', 'krish'], dtype='<U5')

In [48]:
np.char.upper(arr)

array(['SUDH', 'KUMAR', 'PAWAN', 'KRISH'], dtype='<U5')

In [49]:
np.char.title(arr)

array(['Sudh', 'Kumar', 'Pawan', 'Krish'], dtype='<U5')

In [50]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar', 'Pawan', 'Krish'], dtype='<U5')

In [51]:
# Numpy  - Mathematical Functions.


In [52]:
arr1

array([[6, 6, 6, 9],
       [8, 6, 7, 4],
       [2, 9, 1, 5]])

In [53]:
np.sin(arr1)

array([[-0.2794155 , -0.2794155 , -0.2794155 ,  0.41211849],
       [ 0.98935825, -0.2794155 ,  0.6569866 , -0.7568025 ],
       [ 0.90929743,  0.41211849,  0.84147098, -0.95892427]])

In [54]:
np.cos(arr1)

array([[ 0.96017029,  0.96017029,  0.96017029, -0.91113026],
       [-0.14550003,  0.96017029,  0.75390225, -0.65364362],
       [-0.41614684, -0.91113026,  0.54030231,  0.28366219]])

In [56]:
np.tan(arr1)

array([[-0.29100619, -0.29100619, -0.29100619, -0.45231566],
       [-6.79971146, -0.29100619,  0.87144798,  1.15782128],
       [-2.18503986, -0.45231566,  1.55740772, -3.38051501]])

In [57]:
np.tanh(arr1)

array([[0.99998771, 0.99998771, 0.99998771, 0.99999997],
       [0.99999977, 0.99998771, 0.99999834, 0.9993293 ],
       [0.96402758, 0.99999997, 0.76159416, 0.9999092 ]])

In [58]:
np.log10(arr1)

array([[0.77815125, 0.77815125, 0.77815125, 0.95424251],
       [0.90308999, 0.77815125, 0.84509804, 0.60205999],
       [0.30103   , 0.95424251, 0.        , 0.69897   ]])

In [59]:
np.exp(arr1)

array([[4.03428793e+02, 4.03428793e+02, 4.03428793e+02, 8.10308393e+03],
       [2.98095799e+03, 4.03428793e+02, 1.09663316e+03, 5.45981500e+01],
       [7.38905610e+00, 8.10308393e+03, 2.71828183e+00, 1.48413159e+02]])

In [60]:
np.sqrt(arr1)

array([[2.44948974, 2.44948974, 2.44948974, 3.        ],
       [2.82842712, 2.44948974, 2.64575131, 2.        ],
       [1.41421356, 3.        , 1.        , 2.23606798]])

In [61]:
np.power(arr1,2)

array([[36, 36, 36, 81],
       [64, 36, 49, 16],
       [ 4, 81,  1, 25]])

In [62]:
np.mean(arr1)

5.75

In [63]:
np.median(arr1)

6.0

In [64]:
np.std(arr1)

2.384848003542364

In [65]:
np.var(arr1)

5.6875

In [66]:
np.min(arr1)

1

In [67]:
np.max(arr1)

9