In [1]:
# Numpy = Numerical Python
# In numpy we deals with arrays and metrixes

In [2]:
import numpy as np


In [4]:
l = [1,2,3,4,5,6,7,8]


In [5]:
ar = np.array(l)

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2,3],
         [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a = [1,2,4,5,3]
np.asanyarray(a)

array([1, 2, 4, 5, 3])

In [10]:
# we can use any method for convert into array


In [11]:
mat = np.matrix(a)

In [12]:
mat

matrix([[1, 2, 4, 5, 3]])

In [13]:
# Matrix is bydefault 2-d
# Metrix is subset of array

In [14]:
np.asanyarray(mat)
# Not convert into the arrya. Since it convet any list into array ,  and metrix is a subclass of an array means metrix is another form of array.

matrix([[1, 2, 4, 5, 3]])

In [15]:
a = np.array(l)

In [16]:
c  = a

In [17]:
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
c[0]

1

In [20]:
c[0] = 1000

In [21]:
c

array([1000,    2,    3,    4,    5,    6,    7,    8])

In [22]:
a

array([1000,    2,    3,    4,    5,    6,    7,    8])

In [23]:
# c point to same location in the memmory same as a , so if we change any in the c , it will reflect in the main memory . 
# Shallow copy 


In [24]:
d = np.copy(a)

In [25]:
d

array([1000,    2,    3,    4,    5,    6,    7,    8])

In [26]:
a

array([1000,    2,    3,    4,    5,    6,    7,    8])

In [27]:
a[2] = 400

In [28]:
d

array([1000,    2,    3,    4,    5,    6,    7,    8])

In [29]:
# Here a is copy in the d in new location , so if we changes in the a it will not reflect in the d array
# Deep copy

In [30]:
np.fromfunction(lambda i,j : i==j , (3,3))
# 3,3 -->> 3*3 metrix


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
np.fromfunction(lambda i,j : i*j , (3,3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
iterable = (i*i for i in range(5))

In [33]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [34]:
np.fromstring('312 34 23 534 232' , sep = ' ')

array([312.,  34.,  23., 534., 232.])

In [35]:
np.fromstring('23,34,212,3453,32',sep = ',')

array([  23.,   34.,  212., 3453.,   32.])

In [36]:
#Numpy - Data Types 

In [37]:
l = [3,2,5,6,6,3,2]


In [38]:
ar = np.array(l)

In [39]:
ar

array([3, 2, 5, 6, 6, 3, 2])

In [40]:
ar.ndim

1

In [41]:
ar2 = np.array([[3,3,5,5],[5,3,7,4]])

In [42]:
ar2

array([[3, 3, 5, 5],
       [5, 3, 7, 4]])

In [43]:
ar.size

7

In [44]:
ar2.size

8

In [45]:
ar.shape

(7,)

In [46]:
ar2.shape

(2, 4)

In [47]:
ar.dtype

dtype('int64')

In [48]:
ar2.dtype

dtype('int64')

In [49]:
ar22 = np.array([(1.2,32,34),(64,3,4)])

In [50]:
ar22

array([[ 1.2, 32. , 34. ],
       [64. ,  3. ,  4. ]])

In [51]:
ar22.dtype

dtype('float64')

In [52]:
range(10)

range(0, 10)

In [53]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
list(range(0.5 , 5))

TypeError: 'float' object cannot be interpreted as an integer

In [55]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [56]:
np.arange(2.3,5.6,0.2)

array([2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7,
       4.9, 5.1, 5.3, 5.5])

In [58]:
list(np.arange(2.3,5.6,0.2))

[2.3,
 2.5,
 2.7,
 2.9000000000000004,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.700000000000001,
 3.9000000000000012,
 4.100000000000001,
 4.300000000000002,
 4.500000000000002,
 4.700000000000002,
 4.900000000000002,
 5.100000000000002,
 5.3000000000000025,
 5.500000000000003]

In [60]:
np.linspace(1,5,10)
# it will produce n data between the give range 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [61]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [62]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.zeros((3,4,5))
# 3-d

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [66]:
np.zeros((2,4,3,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [71]:
ar4 = np.zeros((5,3,3,3))

In [72]:
ar4.ndim

4

In [73]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [5]:
one = np.ones((2,3,3))

In [6]:
one

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
one+5

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [8]:
one*5

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [9]:
np.empty((3,5))

array([[4.65276984e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.95238591e-310]])

In [10]:
np.eye(4)
# except the diogonal all elements are zeros

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.linspace(2,4,20)
# divide range into equal n parts

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [12]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [13]:
np.logspace(2,5,10 , base =2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [14]:
np.random.randn(3,4)

array([[ 1.2483099 , -1.29392634,  1.21449557, -0.19265139],
       [-1.77858355, -0.06552392, -0.43359423, -0.92337424],
       [ 1.54669211,  2.95968168, -0.87727597,  0.16514518]])

In [15]:
np.random.randn(2,3,4)

array([[[-7.78709734e-01, -1.44487505e+00,  7.90171116e-01,
          6.47762750e-01],
        [ 2.76836173e+00, -1.33598946e+00,  3.01806292e-01,
         -3.29234826e-02],
        [ 8.44558160e-01,  7.61229981e-02,  9.61214125e-01,
         -1.52738859e-01]],

       [[ 1.45566734e+00, -3.68276880e-01,  1.86264337e+00,
          6.22836859e-01],
        [ 8.19283151e-01,  3.03308946e-02, -1.60904169e+00,
          5.62973514e-01],
        [-7.98524043e-01,  7.98209703e-01,  2.18455753e+00,
          2.52909443e-03]]])

In [16]:
arr = np.random.randn(3,4)
# Here mean of element is equal to zero and std is one

In [17]:
import pandas as pd

In [18]:
pd.DataFrame(arr)

0         1         2         3
0  0.381879 -1.356621  1.370295 -2.168194
1 -0.149477  0.315134 -0.177308 -0.384109
2  0.667880  1.973687  0.933447 -0.361561

In [19]:
np.random.rand(3,4)


array([[0.00946007, 0.4204764 , 0.42973433, 0.77639423],
       [0.5460897 , 0.34381875, 0.96785749, 0.09280734],
       [0.45666271, 0.06134333, 0.4576825 , 0.7503869 ]])

In [20]:
np.random.randint(1,100,(3,4))

array([[ 5, 86, 59, 69],
       [ 4, 30, 88, 77],
       [96, 48, 71, 67]])

In [21]:
pd.DataFrame(np.random.randint(1,1000,(500,50)))

0    1    2    3    4    5    6    7    8    9   ...   40   41   42  \
0    246  524  361  583  344  276  179   99  499  654  ...  865   60  843   
1    679  550  271   94  435  476  100  614  382   65  ...  600  397  903   
2    234  422  697  189  278  563  584  807  267  305  ...   74   82  920   
3    576  462  162  329   59  129  599  370  881  781  ...  250  443  794   
4    232  772  244  453  547  236  288  667  225  215  ...  244   34  802   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
495  644  374  165  207  410  423  905  848   49  897  ...  389  638  185   
496  296  710  845  983  392  159  640  952  233  525  ...  604  418  964   
497  184  808  891  891  354  351  946  369  505  899  ...  146  634  699   
498  595  244  300  434  232  363  349  372  263  863  ...  445  858  389   
499  198  205  756   75  283  349   68  720   63  687  ...   54  422  262   

      43   44   45   46   47   48   49  
0    619  883  680  565  852  919  785  
1    183  250   10  670  285  482  943  
2    951  267  960  152  889  870  383  
3    441  294  224  915  807  240  532  
4    499  614  838  233  593   61   73  
..   ...  ...  ...  ...  ...  ...  ...  
495  251  583  980    6  793   93  452  
496   60  236    9  100  388  237  488  
497  702  209  477  168  252  198  943  
498    7  199  617  988  889  142  554  
499  903  139  463  959  359  992  482  

[500 rows x 50 columns]

In [23]:
pd.DataFrame(np.random.randint(1,1000,(500,50))).to_csv('test.csv')


In [24]:
arr = np.random.rand(3,4)

In [25]:
arr

array([[0.92087675, 0.18504208, 0.09642202, 0.61034129],
       [0.5068335 , 0.55921064, 0.90276258, 0.19663501],
       [0.77587434, 0.51360548, 0.97095379, 0.01336972]])

In [27]:
# How to change sape of the array
arr.reshape(6,2)
# but total element must be equal to the array elements

array([[0.92087675, 0.18504208],
       [0.09642202, 0.61034129],
       [0.5068335 , 0.55921064],
       [0.90276258, 0.19663501],
       [0.77587434, 0.51360548],
       [0.97095379, 0.01336972]])

In [28]:
arr.reshape(6,7)

ValueError: cannot reshape array of size 12 into shape (6,7)

In [30]:
arr.reshape(6,-1)

array([[0.92087675, 0.18504208],
       [0.09642202, 0.61034129],
       [0.5068335 , 0.55921064],
       [0.90276258, 0.19663501],
       [0.77587434, 0.51360548],
       [0.97095379, 0.01336972]])

In [31]:
arr.reshape(6,-34)

array([[0.92087675, 0.18504208],
       [0.09642202, 0.61034129],
       [0.5068335 , 0.55921064],
       [0.90276258, 0.19663501],
       [0.77587434, 0.51360548],
       [0.97095379, 0.01336972]])

In [35]:
# How to featch data
arr1 = arr.reshape(6,2)

In [36]:
arr1

array([[0.92087675, 0.18504208],
       [0.09642202, 0.61034129],
       [0.5068335 , 0.55921064],
       [0.90276258, 0.19663501],
       [0.77587434, 0.51360548],
       [0.97095379, 0.01336972]])

In [37]:
arr1[1][1]

0.6103412904482449

In [38]:
arr1[2:5]

array([[0.5068335 , 0.55921064],
       [0.90276258, 0.19663501],
       [0.77587434, 0.51360548]])

In [39]:
arr1[2:5 , 1]

array([0.55921064, 0.19663501, 0.51360548])

In [41]:
arr = np.random.randint(1,100,(5,5))

In [42]:
arr

array([[ 7, 22, 81, 87, 27],
       [58, 23, 75, 61, 41],
       [ 6,  3, 83, 83, 73],
       [ 4, 92,  4, 40, 97],
       [65, 52, 98, 67, 92]])

In [43]:
# fetch data which is greather that 50
arr>50

array([[False, False,  True,  True, False],
       [ True, False,  True,  True, False],
       [False, False,  True,  True,  True],
       [False,  True, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [44]:
arr[arr>50]

array([81, 87, 58, 75, 61, 83, 83, 73, 92, 97, 65, 52, 98, 67, 92])

In [45]:
arr[2:4 , [1,2]]

array([[ 3, 83],
       [92,  4]])

In [46]:
arr[0][0] = 500

In [47]:
arr

array([[500,  22,  81,  87,  27],
       [ 58,  23,  75,  61,  41],
       [  6,   3,  83,  83,  73],
       [  4,  92,   4,  40,  97],
       [ 65,  52,  98,  67,  92]])

In [49]:
arr1  = np.random.randint(1,3,(3,3))
arr2  = np.random.randint(1,3,(3,3))

In [50]:
arr1

array([[2, 1, 1],
       [2, 1, 2],
       [1, 2, 2]])

In [51]:
arr2

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [52]:
arr1+arr2

array([[4, 2, 3],
       [4, 2, 4],
       [2, 4, 3]])

In [53]:
arr1-arr2

array([[ 0,  0, -1],
       [ 0,  0,  0],
       [ 0,  0,  1]])

In [54]:
arr1/arr2

array([[1. , 1. , 0.5],
       [1. , 1. , 1. ],
       [1. , 1. , 2. ]])

In [55]:
arr1*arr2
# It is not a metrix multiplation , it is simple indexing multiplation

array([[4, 1, 2],
       [4, 1, 4],
       [1, 4, 2]])

In [56]:
arr1@arr2
# it ie metrix multiplation

array([[7, 5, 7],
       [8, 7, 8],
       [8, 7, 8]])

In [58]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [59]:
arr1+100

array([[102, 101, 101],
       [102, 101, 102],
       [101, 102, 102]])

In [60]:
arr1**2
# power of two

array([[4, 1, 1],
       [4, 1, 4],
       [1, 4, 4]])

In [61]:
# Numpyn -  Broadcasting

In [63]:
arr = np.zeros((4,4))

In [66]:
row = np.array([1,2,3,4])

In [67]:
row

array([1, 2, 3, 4])

In [68]:
arr + row
# addditon on all the row value , 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [69]:
# how to add column wise
row.T
# not able to tranpose , because it is one dimentional

array([1, 2, 3, 4])

In [70]:
col = np.array([[1,2,4,5]])

In [71]:
col.T

array([[1],
       [2],
       [4],
       [5]])

In [73]:
arr+col.T
# column wise broadcasting

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [75]:
arr1 = np.random.randint(1,4,(3,4))

In [76]:
arr1

array([[1, 1, 1, 3],
       [2, 2, 1, 3],
       [2, 3, 3, 3]])

In [77]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        , 1.73205081],
       [1.41421356, 1.41421356, 1.        , 1.73205081],
       [1.41421356, 1.73205081, 1.73205081, 1.73205081]])

In [78]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183,  2.71828183, 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  2.71828183, 20.08553692],
       [ 7.3890561 , 20.08553692, 20.08553692, 20.08553692]])

In [79]:
np.log10(arr1)

array([[0.        , 0.        , 0.        , 0.47712125],
       [0.30103   , 0.30103   , 0.        , 0.47712125],
       [0.30103   , 0.47712125, 0.47712125, 0.47712125]])

In [ ]:
# Images is in the form of the array . Colorful images is 2-d  , black and white is 1-d