In [1]:
# Sort , Searching and counting funcitons

In [2]:
import numpy as np

In [4]:
arr = np.array([3,4,56,7,4,2,3,5])

In [5]:
np.sort(arr)

array([ 2,  3,  3,  4,  4,  5,  7, 56])

In [7]:
np.searchsorted(arr , 34)
# data kha par best fit hoga in order to sorting the array

8

In [8]:
arr1 = np.array([0,3,32,12,5,0,7,0,0,6,0])

In [11]:
np.count_nonzero(arr1)

6

In [13]:
np.where(arr1>6)
# give index of data where condition satisified

(array([2, 3, 6]),)

In [15]:
np.extract(arr1>3 , arr1)

array([32, 12,  5,  7,  6])

In [16]:
arr1

array([ 0,  3, 32, 12,  5,  0,  7,  0,  0,  6,  0])

In [17]:
arr.byteswap()
# Swap the bytes of the array elements

array([ 216172782113783808,  288230376151711744, 4035225266123964416,
        504403158265495552,  288230376151711744,  144115188075855872,
        216172782113783808,  360287970189639680])

In [18]:
# Numpy -  Copies  and Views

In [21]:
arr

array([ 3,  4, 56,  7,  4,  2,  3,  5])

In [19]:
a = np.copy(arr)
# deep copy

In [28]:
b = arr.view()
# shallow copy

In [29]:
b[0] = 23

In [30]:
b

array([23,  4, 56,  7,  4,  2,  3,  5])

In [31]:
arr

array([23,  4, 56,  7,  4,  2,  3,  5])

In [32]:
a[3]=23423

In [33]:
a

array([    3,     4,    56, 23423,     4,     2,     3,     5])

In [34]:
b

array([23,  4, 56,  7,  4,  2,  3,  5])

In [35]:
# Numpy  - Metrix Library
import numpy.matlib as nm
# it is similer to numpy , but it is generate metrix

In [36]:
nm.zeros(5)
# now it will generate metrix, not array

matrix([[0., 0., 0., 0., 0.]])

In [38]:
nm.ones((4,5))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [39]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [41]:
# Linerar Algebra
arr1 = np.random.randint([[3,4],[4,5]])
arr1

array([[2, 0],
       [1, 1]])

In [42]:
arr2 = np.random.randint([[3,4],[4,5]])
arr2

array([[2, 0],
       [3, 0]])

In [43]:
np.dot(arr1,arr2)
# similer to metrix multiplation

array([[4, 0],
       [5, 0]])

In [44]:
arr1@arr2

array([[4, 0],
       [5, 0]])