In [1]:
# Numpy -  Array manipulation


In [2]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,4))

In [5]:
arr.reshape(1,12)

array([[6, 1, 3, 4, 6, 4, 1, 1, 4, 3, 9, 9]])

In [8]:
arr.reshape(6,-2344234)

array([[6, 1],
       [3, 4],
       [6, 4],
       [1, 1],
       [4, 3],
       [9, 9]])

In [9]:
arr.T 
# Transpose of array
# rotate by 180 degree

array([[6, 6, 4],
       [1, 4, 3],
       [3, 1, 9],
       [4, 1, 9]])

In [11]:
arr.flatten()
# convert array into 1 dimensional


In [12]:
arr1 = np.array([2,3,4,6,7])
arr1

array([2, 3, 4, 6, 7])

In [13]:
arr1.ndim

1

In [18]:
np.expand_dims(arr1 , axis =1)
# convert arrya into n dim

array([[2],
       [3],
       [4],
       [6],
       [7]])

In [21]:
np.expand_dims(arr1,axis =0)

array([[2, 3, 4, 6, 7]])

In [23]:
# arr.squeeze()
np.squeeze(arr)

array([[6, 1, 3, 4],
       [6, 4, 1, 1],
       [4, 3, 9, 9]])

In [24]:
data  = np.array([[1],[2],[3]])

In [25]:
data

array([[1],
       [2],
       [3]])

In [26]:
np.squeeze(data)

array([1, 2, 3])

In [27]:
arr1

array([2, 3, 4, 6, 7])

In [28]:
np.repeat(arr1 , 3)

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 6, 6, 6, 7, 7, 7])

In [31]:
arr1

array([2, 3, 4, 6, 7])

In [32]:
np.roll(arr1 , 2)
# rotate data by 2 position

array([6, 7, 2, 3, 4])

In [33]:
np.diag(arr1)

array([[2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 7]])

In [34]:
# Numpy  - Binary Operations

In [37]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [38]:
arr1

array([[8, 6, 3, 1],
       [3, 6, 5, 6],
       [5, 6, 5, 6]])

In [39]:
arr2

array([[3, 9, 8, 2],
       [8, 1, 5, 8],
       [1, 1, 1, 8]])

In [40]:
arr1+arr2

array([[11, 15, 11,  3],
       [11,  7, 10, 14],
       [ 6,  7,  6, 14]])

In [41]:
arr1%arr2
# remender operation

array([[2, 6, 3, 1],
       [3, 0, 0, 6],
       [0, 0, 0, 6]])

In [42]:
arr1**arr2

array([[     512, 10077696,     6561,        1],
       [    6561,        6,     3125,  1679616],
       [       5,        6,        5,  1679616]])

In [43]:
arr1 & arr2

array([[0, 0, 0, 0],
       [0, 0, 5, 0],
       [1, 0, 1, 0]])

In [44]:
~arr1

array([[-9, -7, -4, -2],
       [-4, -7, -6, -7],
       [-6, -7, -6, -7]])

In [45]:
arr1 | arr2

array([[11, 15, 11,  3],
       [11,  7,  5, 14],
       [ 5,  7,  5, 14]])

In [46]:
arr1>arr2

array([[ True, False, False, False],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [48]:
# Numpy  - String Function
arr = np.array(['sudh' , 'kumar'])
arr

array(['sudh', 'kumar'], dtype='<U5')

In [49]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [50]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [51]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [52]:
# Numpy  - Mathematical Functions.

In [53]:
arr1

array([[8, 6, 3, 1],
       [3, 6, 5, 6],
       [5, 6, 5, 6]])

In [55]:
np.sin(arr1)

array([[ 0.98935825, -0.2794155 ,  0.14112001,  0.84147098],
       [ 0.14112001, -0.2794155 , -0.95892427, -0.2794155 ],
       [-0.95892427, -0.2794155 , -0.95892427, -0.2794155 ]])

In [56]:
np.cos(arr1)

array([[-0.14550003,  0.96017029, -0.9899925 ,  0.54030231],
       [-0.9899925 ,  0.96017029,  0.28366219,  0.96017029],
       [ 0.28366219,  0.96017029,  0.28366219,  0.96017029]])

In [57]:
np.tan(arr1)

array([[-6.79971146, -0.29100619, -0.14254654,  1.55740772],
       [-0.14254654, -0.29100619, -3.38051501, -0.29100619],
       [-3.38051501, -0.29100619, -3.38051501, -0.29100619]])

In [58]:
np.tanh(arr1)

array([[0.99999977, 0.99998771, 0.99505475, 0.76159416],
       [0.99505475, 0.99998771, 0.9999092 , 0.99998771],
       [0.9999092 , 0.99998771, 0.9999092 , 0.99998771]])

In [60]:
np.log10(arr1)

array([[0.90308999, 0.77815125, 0.47712125, 0.        ],
       [0.47712125, 0.77815125, 0.69897   , 0.77815125],
       [0.69897   , 0.77815125, 0.69897   , 0.77815125]])

In [62]:
np.exp(arr1)

array([[2.98095799e+03, 4.03428793e+02, 2.00855369e+01, 2.71828183e+00],
       [2.00855369e+01, 4.03428793e+02, 1.48413159e+02, 4.03428793e+02],
       [1.48413159e+02, 4.03428793e+02, 1.48413159e+02, 4.03428793e+02]])

In [63]:
np.sqrt(arr1)

array([[2.82842712, 2.44948974, 1.73205081, 1.        ],
       [1.73205081, 2.44948974, 2.23606798, 2.44948974],
       [2.23606798, 2.44948974, 2.23606798, 2.44948974]])

In [65]:
np.power(arr1 , 3)

array([[512, 216,  27,   1],
       [ 27, 216, 125, 216],
       [125, 216, 125, 216]])

In [66]:
np.mean(arr1)

5.0

In [68]:
np.median(arr1)

5.5

In [69]:
np.std(arr1)

1.7795130420052185

In [70]:
np.var(arr1)

3.1666666666666665

In [71]:
np.min(arr1)

1

In [72]:
np.max(arr1)

8

In [73]:
arr1.min()

1

In [74]:
arr1.mean()

5.0