In [1]:
# Numpy  -  Numerical Python
# it is very important libray in terms of data processing


In [2]:
import numpy as np

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
l = [2,3,4,5,6,7];
# convert list into array
np.array(l)

array([2, 3, 4, 5, 6, 7])

In [7]:
ar = np.array(l)
type(ar)

numpy.ndarray

In [12]:
arr2 = np.array([[3,5,6,67,7],
         [7,54,3,5,7]]
)
arr2


numpy.ndarray

In [13]:
type(arr2)

numpy.ndarray

In [14]:
np.asarray(l)

array([2, 3, 4, 5, 6, 7])

In [15]:
a  = [4,2,54,6,3]
np.asanyarray(a)

array([ 4,  2, 54,  6,  3])

In [18]:
# np.array  ,  np.asarray , np.asanyarray  all are use to convert list into array
b = np.matrix(a)
# metrix is by default 2d array . Ans metrix is subset or subclass of array

In [19]:
b

matrix([[ 4,  2, 54,  6,  3]])

In [21]:
np.asanyarray(b)
# can't be able to convert metrix into array . Because matrix is already subset of array

matrix([[ 4,  2, 54,  6,  3]])

In [22]:
a = np.array(l)

In [25]:
c = a
# Now referance of a is passed to the c . And if we do any change in a or c it will reflect to each other
# Shallow Copy
a

array([2, 3, 4, 5, 6, 7])

In [26]:
c

array([2, 3, 4, 5, 6, 7])

In [27]:
c[0] = 1000

In [28]:
c

array([1000,    3,    4,    5,    6,    7])

In [29]:
a

array([1000,    3,    4,    5,    6,    7])

In [30]:
d = np.copy(a)

In [31]:
d

array([1000,    3,    4,    5,    6,    7])

In [32]:
a

array([1000,    3,    4,    5,    6,    7])

In [33]:
a [1] = 400

In [34]:
a

array([1000,  400,    4,    5,    6,    7])

In [35]:
d

array([1000,    3,    4,    5,    6,    7])

In [36]:
#  now not reflact changes in each other , because copy of a is passed to d , not address . 
# Deep Copy


In [37]:
# In Numpy there are various function in terms to generate various array , and perfrom operation on arrry
np.fromfunction(lambda i, j : i==j , (3,3))
# i ,j start with zero . 3*3 Metrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [41]:
iterable = (i*i for i in range(5))

In [42]:
np.fromiter(iterable , float)
# Now we can iter over it

array([ 0.,  1.,  4.,  9., 16.])

In [43]:
np.fromstring('32 34 65 23 76' , sep = ' ')

array([32., 34., 65., 23., 76.])

In [44]:
np.fromstring('32,34,65,23, 76' , sep = ',')

array([32., 34., 65., 23., 76.])

In [45]:
# Numpy - Data Types
l  = [4,2,4,56,2]
arr = np.array(l)

In [46]:
arr

array([ 4,  2,  4, 56,  2])

In [47]:
arr.ndim
# ndim is used for figure out the dimention

1

In [48]:
arr2 = np.array([[2,3,54,6] , [7,4,2,4]])

In [49]:
arr2

array([[ 2,  3, 54,  6],
       [ 7,  4,  2,  4]])

In [50]:
arr2.ndim

2

In [51]:
arr.size

5

In [52]:
arr2.size

8

In [53]:
arr.shape

(5,)

In [54]:
arr2.shape

(2, 4)

In [55]:
arr.dtype

dtype('int64')

In [56]:
arr2.dtype

dtype('int64')

In [60]:
arr2 = np.array([(2.6,3,4) , (6,4,2)])

In [61]:
arr2

array([[2.6, 3. , 4. ],
       [6. , 4. , 2. ]])

In [62]:
arr2.dtype

dtype('float64')

In [63]:
range(5)

range(0, 5)

In [64]:
list(range(5))

[0, 1, 2, 3, 4]

In [66]:
list(range(0.1,5))
# range can't work with floating point 

TypeError: 'float' object cannot be interpreted as an integer

In [68]:
np.arange(2.3 , 6.7)
# Dy Default jump is equal to 1

array([2.3, 3.3, 4.3, 5.3, 6.3])

In [69]:
np.arange(2.3,8.5,0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6, 5.9,
       6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. , 8.3])

In [70]:
list(np.arange(2.3,8.5,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998,
 5.599999999999998,
 5.899999999999998,
 6.1999999999999975,
 6.499999999999997,
 6.799999999999997,
 7.099999999999997,
 7.399999999999997,
 7.699999999999997,
 7.9999999999999964,
 8.299999999999997]

In [73]:
np.linspace(1,5,10)
# divide data 1 to 5 in 10 equal parts

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [74]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [76]:
np.zeros((3,4))
# 2 dimention

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.zeros((3,4,2))
# 3 dimension array
# we have 4*2 three such kind of materics
# search google for more referance

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [83]:
np.zeros((3,4,2,3))
# 44 dimension rrrya
# it is useful in computer vision and 3d vision 
# images are stored in multi dimension array

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [84]:
np.ones(4)

array([1., 1., 1., 1.])

In [85]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.ones((2,3,4,7))

array([[[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]]])

In [93]:
one = np.ones((2,3,4))
one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [94]:
one+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [95]:
one*5

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [98]:
np.empty((3,6))
# it will  produce empty metrics

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [100]:
np.eye(4)
# create identity metrics

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [103]:
np.logspace(2,4,10 ,  base = 2)
# by default base in 10

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [108]:
arr = np.random.randn(3,4)
# it will generated such kind of data  where mean(average) is equal to 0 and std is equal to 1
arr

array([[ 0.93811024, -0.99978917, -0.02662667, -0.79405834],
       [-1.93201822, -0.09639361, -3.25304649, -0.85950909],
       [ 0.78161003,  0.20580533,  0.09231403, -1.33632934]])

In [106]:
import pandas as pd

In [109]:
pd.DataFrame(arr)

0         1         2         3
0  0.938110 -0.999789 -0.026627 -0.794058
1 -1.932018 -0.096394 -3.253046 -0.859509
2  0.781610  0.205805  0.092314 -1.336329

In [110]:
np.random.rand(3,4)

array([[0.11418132, 0.16656017, 0.47696813, 0.47042339],
       [0.56553959, 0.83099661, 0.71981086, 0.2461764 ],
       [0.48919306, 0.93306002, 0.02682092, 0.02743802]])

In [112]:
np.random.randint(1,100,(3,4))
# Produce only integer data

array([[84, 35, 97, 54],
       [96, 45, 12, 42],
       [61, 90, 34, 33]])

In [114]:
pd.DataFrame(np.random.randint(1,100,(300,900))).to_csv('rv_test.csv')

In [117]:
arr = np.random.rand(3,4)
arr

array([[0.1969869 , 0.70385172, 0.64488452, 0.24900081],
       [0.10640746, 0.8718828 , 0.44252272, 0.05441892],
       [0.38138217, 0.10489355, 0.2082706 , 0.03719498]])

In [119]:
arr.reshape(6,2) 
# Data must be multiple of total data

array([[0.1969869 , 0.70385172],
       [0.64488452, 0.24900081],
       [0.10640746, 0.8718828 ],
       [0.44252272, 0.05441892],
       [0.38138217, 0.10489355],
       [0.2082706 , 0.03719498]])

In [120]:
arr.reshape(6,-1)
# we can give minus index to the array , it will understand automatically base on 1st coordinate

array([[0.1969869 , 0.70385172],
       [0.64488452, 0.24900081],
       [0.10640746, 0.8718828 ],
       [0.44252272, 0.05441892],
       [0.38138217, 0.10489355],
       [0.2082706 , 0.03719498]])

In [124]:
arr1=  arr.reshape(6,-5)

In [125]:
arr1[1]

array([0.64488452, 0.24900081])

In [126]:
arr1[1][1]

0.24900080955232962

In [131]:
arr1[2:5]

array([[0.10640746, 0.8718828 ],
       [0.44252272, 0.05441892],
       [0.38138217, 0.10489355]])

In [132]:
arr1[2:5][1][1]

0.05441891569500379

In [137]:
arr = np.random.randint(1,100,(5,5))

In [138]:
# Featch data only greated then 50
arr>50

array([[ True, False,  True,  True,  True],
       [ True,  True, False, False, False],
       [False,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [ True, False,  True, False,  True]])

In [139]:
arr[arr>50]

array([81, 84, 72, 84, 67, 75, 77, 92, 54, 54, 69, 80, 94, 64, 86, 69])

In [140]:
arr

array([[81, 39, 84, 72, 84],
       [67, 75, 44, 15, 23],
       [11, 77, 22, 92, 54],
       [15, 54, 69, 80, 94],
       [64, 43, 86, 40, 69]])

In [143]:
arr[1:3 , 1:3]

array([[75, 44],
       [77, 22]])

In [144]:
arr[0,0]

81

In [149]:
arr[0,0]=  423
# arr[0][0] = 432  
# both are similer

In [150]:
arr

array([[423,  39,  84,  72,  84],
       [ 67,  75,  44,  15,  23],
       [ 11,  77,  22,  92,  54],
       [ 15,  54,  69,  80,  94],
       [ 64,  43,  86,  40,  69]])

In [151]:
arr1 = np.random.randint(1,5,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [152]:
arr1

array([[3, 1, 4],
       [2, 2, 3],
       [3, 2, 3]])

In [153]:
arr2

array([[2, 1, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [154]:
arr1+arr2

array([[5, 2, 5],
       [3, 4, 5],
       [4, 3, 5]])

In [157]:
arr1*arr2
# it is not matrix multiplation , it multiply index by index

array([[6, 1, 4],
       [2, 4, 6],
       [3, 2, 6]])

In [159]:
arr1@arr2
# now it will matrix multiplation

array([[11,  9, 13],
       [ 9,  9, 12],
       [11, 10, 13]])

In [156]:
arr1/arr2

array([[1.5, 1. , 4. ],
       [2. , 1. , 1.5],
       [3. , 2. , 1.5]])

In [158]:
arr1@arr2

array([[11,  9, 13],
       [ 9,  9, 12],
       [11, 10, 13]])

In [160]:
arr1/0

/tmp/ipykernel_88/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [161]:
arr1+1000

array([[1003, 1001, 1004],
       [1002, 1002, 1003],
       [1003, 1002, 1003]])

In [162]:
arr1**2

array([[ 9,  1, 16],
       [ 4,  4,  9],
       [ 9,  4,  9]])

In [167]:
arr2 = np.zeros((4,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [168]:
row = np.array([3,54,6,2])
row

array([ 3, 54,  6,  2])

In [169]:
arr2+row
# it will be add in each rows . It is called Broadcasting


array([[ 3., 54.,  6.,  2.],
       [ 3., 54.,  6.,  2.],
       [ 3., 54.,  6.,  2.],
       [ 3., 54.,  6.,  2.]])

In [170]:
row.shape

(4,)

In [176]:
# ADd column wise
# For transpose of array it must be 2 dimension
col = np.array([[3,5,6,2]])
col.T

array([[3],
       [5],
       [6],
       [2]])

In [179]:
arr2+col.T
# Column wise broadcasting

array([[3., 3., 3., 3.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [2., 2., 2., 2.]])

In [180]:
arr3 = np.random.randint(1,4,(3,4))


In [181]:
arr3

array([[3, 2, 2, 2],
       [2, 1, 2, 2],
       [2, 2, 1, 2]])

In [182]:
np.sqrt(arr3)

array([[1.73205081, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        , 1.41421356]])

In [183]:
np.exp(arr3)

array([[20.08553692,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 ,  2.71828183,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 ,  2.71828183,  7.3890561 ]])

In [184]:
np.log(arr3)

array([[1.09861229, 0.69314718, 0.69314718, 0.69314718],
       [0.69314718, 0.        , 0.69314718, 0.69314718],
       [0.69314718, 0.69314718, 0.        , 0.69314718]])